language: java
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: heroku
  app: sparkexamplesmaaguero
  api_key:
    secure: Lo0ChoYmcG1phJajIOnw+lAcQB56px3k+BmXEXLh7CggzPLIURRsrkrP5VpEDhHWbXZ5ZTPxYQ9kT+06hnpz9q/UPznCqTRjvbT4dxfjUU3BMM7D3CV/nKgKriylkQTCUxXpEoAwUfbzaKfIazPMbAFOO2oPvVu5FSWuIY11bzX56rHUJfX6PXN5Gr7Ti2fG2okrs5ZakSygbBDsOhOAE0R62JRBNUdh7FIH3RQrASfu/86X9gEDZ0RlnXlMj1I8funRvSXRUQ5k+n1+dlNk4vayk+53chGqRCYfJx1mtUUdZtkB9J+Sy/H164+0MbIlufTW78fI/w+pX2qVvYGLt8cFvbwnvEG6k19asE2jVs7uXEF9nuJCcizlmQoZsJww+7YC2AYSB2ioIsRwFC4Y8Zz7xwVfLOJ/k5FXbQ7EqakQm3G2kLqicN7TAGGB5F17oGk1U5GsyDBgd70m46Mt5uV7N7UOS5n1F4M5K2MKyVimU0oGH9j9Co1yAnKALFUdo/nfTpyPc/B/QfunPQDf+jyctvuX2aTHA1fZQYhLZeR25nUHQJonseSaFuVtYiXwRTts01WVtw/ndQgzje1PdQ5jQdrAaNxGvsIkVpoZz9+NuWvE2AyMWmu1McIduqaKlNNaeLFELHqfDkExJcngLgKOpWa/1HgRXU8E7o9GEKM=
